#!/usr/bin/env python3
import re
import subprocess
import os

# Find repo root regardless of where the script is run from
def get_repo_root():
    try:
        return subprocess.check_output(
            ['git', 'rev-parse', '--show-toplevel'],
            cwd=os.getcwd(),
            universal_newlines=True
        ).strip()
    except subprocess.CalledProcessError:
        # Fallback: walk up from cwd until we find a known marker
        path = os.getcwd()
        while path != os.path.dirname(path):
            if os.path.exists(os.path.join(path, 'build.gradle')) or \
               os.path.exists(os.path.join(path, '.git')):
                return path
            path = os.path.dirname(path)
        raise Exception("Could not find repo root")

inp = subprocess.run(['pbpaste'], capture_output=True, text=True).stdout

pattern = re.compile(r'export\s+(?P<key>\w+)=["\'](?P<val>.*?)["\']')
env = {m.group('key'): m.group('val') for m in pattern.finditer(inp)}

if not env:
    print("❌ No AWS exports found in clipboard")
    print("Clipboard content preview:", inp[:100])
else:
    repo_root = get_repo_root()
    creds_path = os.path.join(repo_root, "env-setup", "credentials.env")
    with open(creds_path, "w") as out:
        out.write("# Auto-generated by makeEnvFile.py\n")
        for key, val in env.items():
            out.write(f"{key}={val}\n")
    print(f"✅ {creds_path} written with {len(env)} keys")
